/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_JniDemo */

#ifndef _Included_com_jni_JniDemo
#define _Included_com_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_JniDemo
 * Method:    test
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_JniDemo_test
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jni_JniDemo
 * Method:    getW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jni_JniDemo_getW
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_JniDemo
 * Method:    getH
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jni_JniDemo_getH
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_JniDemo
 * Method:    initEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_JniDemo_initEvent
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_JniDemo
 * Method:    getXX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jni_JniDemo_getXX
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_JniDemo
 * Method:    getYY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jni_JniDemo_getYY
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
